#!/bin/sh
#
# Ensure HWDB is built at startup
#

start() {
        printf "Checking hwdb..."
	if [ ! -f /etc/udev/hwdb.bin ]; then
		echo "Building hwdb..."
		udevadm hwdb --update
	fi
        echo "OK"
}

stop() {
        echo "OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
~

