#!/bin/sh
#
# Add FUSE
#

start() {
        printf "Enabling fust..."

	# Load kmods
	modprobe fuse.ko

	#TODO Add something that automounts?
        echo "OK"
}

stop() {
        echo "OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
~

