patch -p1 < patch1.patch
patch -p1 < patch2.patch          
patch -p1 < patch3.patch
patch -p1 < patch4.patch      
patch -p1 < patch5.patch
patch -p1 < patch6.patch    
patch -p1 < patch7.patch
patch -p1 < patch8.patch  
patch -p1 < patch9.patch
patch -p1 < patch10.patch
